services:
  db:
    container_name: queimadas-db
    build: docker/images/db
    environment:
      - DB_PORT=$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "$DB_PORT:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 15s
      retries: 30
  api:
    build: docker/images/python
    container_name: api
    env_file: .env
    environment:
      - USE_DEV_MODE=${USE_DEV_MODE}
    volumes:
      - ./src/queimadas_api:/usr/src/app
      - ./docker/volumes/data:/data

volumes:
  postgres_data: